param(
  [ValidateSet('up', 'down', 'check', 'quartermaster-start', 'quartermaster-stop')]
  [string]$Command = 'check'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$RuntimeDir = Join-Path $RepoRoot 'ops\pbk-runtime'
$ComposeFile = Join-Path $RuntimeDir 'docker-compose.yml'
$LocalDir = Join-Path $RepoRoot '.pbk-local'
$EnvFile = Join-Path $LocalDir 'pbk-runtime.env'
$QuartermasterVenv = Join-Path $LocalDir 'quartermaster-venv'
$QuartermasterPython = Join-Path $QuartermasterVenv 'Scripts\python.exe'
$QuartermasterPidFile = Join-Path $LocalDir 'quartermaster-code-runner.pid'
$QuartermasterLogFile = Join-Path $LocalDir 'quartermaster-code-runner.log'

function New-PbkSecret([int]$Bytes = 32) {
  $buffer = New-Object byte[] $Bytes
  $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  [Convert]::ToBase64String($buffer)
}

function Ensure-LocalEnv {
  New-Item -ItemType Directory -Force $LocalDir | Out-Null
  if (Test-Path $EnvFile) { return }

  @(
    "# Generated by scripts/pbk-runtime.ps1. Do not commit.",
    "VOIDLLM_ADMIN_KEY=$(New-PbkSecret 36)",
    "VOIDLLM_ENCRYPTION_KEY=$(New-PbkSecret 32)",
    "PBK_CODE_RUNNER_API_KEY=$(New-PbkSecret 36)"
  ) | Set-Content -Path $EnvFile -Encoding utf8
}

function Read-EnvValue([string]$Name) {
  if (-not (Test-Path $EnvFile)) { return '' }
  $line = Get-Content $EnvFile | Where-Object { $_ -match "^$([Regex]::Escape($Name))=" } | Select-Object -First 1
  if (-not $line) { return '' }
  $line.Substring($line.IndexOf('=') + 1).Trim()
}

function Invoke-DockerCompose([string[]]$ComposeArgs) {
  Ensure-LocalEnv
  & docker compose --env-file $EnvFile -f $ComposeFile -p pbk-runtime @ComposeArgs
}

function Test-TcpPort([string]$HostName, [int]$Port) {
  try {
    $client = [Net.Sockets.TcpClient]::new()
    $async = $client.BeginConnect($HostName, $Port, $null, $null)
    $ok = $async.AsyncWaitHandle.WaitOne(2000)
    if ($ok) { $client.EndConnect($async) }
    $client.Close()
    return $ok
  } catch {
    return $false
  }
}

function Invoke-HttpJson([string]$Uri, [hashtable]$Headers = @{}) {
  try {
    Invoke-RestMethod -Uri $Uri -Headers $Headers -TimeoutSec 10
  } catch {
    $null
  }
}

function Test-HttpStatus([string]$Uri) {
  try {
    $response = Invoke-WebRequest -Uri $Uri -UseBasicParsing -TimeoutSec 10
    return [int]$response.StatusCode -ge 200 -and [int]$response.StatusCode -lt 500
  } catch {
    return $false
  }
}

function Ensure-QuartermasterInstall {
  if (-not (Test-Path $QuartermasterPython)) {
    python -m venv $QuartermasterVenv
  }
  & $QuartermasterPython -m pip install --upgrade pip quartermaster-code-runner uvicorn
}

function Ensure-QuartermasterRuntimeImage([string]$RuntimeName = 'python') {
  $imageName = "code-runner-$RuntimeName"
  & cmd.exe /c "docker image inspect $imageName >NUL 2>NUL"
  if ($LASTEXITCODE -eq 0) { return }

  $runtimeDir = (& $QuartermasterPython -c "import pathlib, quartermaster_code_runner; print(pathlib.Path(quartermaster_code_runner.__file__).with_name('runtime'))").Trim()
  $buildPath = Join-Path $runtimeDir $RuntimeName
  if (-not (Test-Path $buildPath)) {
    throw "Quartermaster runtime '$RuntimeName' was not found at $buildPath"
  }

  Write-Host "Building Quartermaster runtime image $imageName..."
  & docker build -t $imageName $buildPath
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to build Quartermaster runtime image $imageName"
  }
}

function Start-Quartermaster {
  Ensure-LocalEnv
  Ensure-QuartermasterInstall
  Ensure-QuartermasterRuntimeImage 'python'

  $apiKey = Read-EnvValue 'PBK_CODE_RUNNER_API_KEY'
  $headers = @{ 'X-API-Key' = $apiKey }
  if (Invoke-HttpJson 'http://127.0.0.1:8011/health' $headers) {
    Write-Host 'Quartermaster Code Runner already healthy on http://127.0.0.1:8011'
    return
  }

$command = @"
`$env:AUTH_TOKEN = '$apiKey'
`$env:CODE_RUNNER_API_KEYS = '$apiKey'
`$env:HOST = '127.0.0.1'
`$env:PORT = '8011'
`$env:DEFAULT_TIMEOUT = '30'
`$env:MAX_TIMEOUT = '120'
`$env:DEFAULT_MEMORY = '256m'
`$env:MAX_MEMORY_MB = '1024'
& '$QuartermasterPython' -m uvicorn quartermaster_code_runner.app:app --host 127.0.0.1 --port 8011 *>> '$QuartermasterLogFile'
"@

  $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command))
  $process = Start-Process -WindowStyle Hidden -FilePath powershell.exe -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', $encoded) -PassThru
  $process.Id | Set-Content -Path $QuartermasterPidFile -Encoding ascii

  $healthy = $false
  foreach ($attempt in 1..20) {
    Start-Sleep -Seconds 2
    if (Invoke-HttpJson 'http://127.0.0.1:8011/health' $headers) {
      $healthy = $true
      break
    }
  }

  if (-not $healthy) {
    throw "Quartermaster Code Runner did not become healthy. See $QuartermasterLogFile"
  }
  Write-Host 'Quartermaster Code Runner healthy on http://127.0.0.1:8011'
}

function Stop-Quartermaster {
  if (Test-Path $QuartermasterPidFile) {
    $processId = [int](Get-Content $QuartermasterPidFile -Raw)
    Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue
    Remove-Item $QuartermasterPidFile -Force -ErrorAction SilentlyContinue
  }

  $listeners = Get-NetTCPConnection -LocalPort 8011 -State Listen -ErrorAction SilentlyContinue
  foreach ($listener in $listeners) {
    Stop-Process -Id $listener.OwningProcess -Force -ErrorAction SilentlyContinue
  }
}

function Test-PbkRuntime {
  Ensure-LocalEnv
  $codeRunnerKey = Read-EnvValue 'PBK_CODE_RUNNER_API_KEY'
  $codeRunnerHeaders = @{ 'X-API-Key' = $codeRunnerKey }

  [pscustomobject]@{
    TemporalGrpc        = Test-TcpPort '127.0.0.1' 7233
    TemporalUi          = Test-HttpStatus 'http://127.0.0.1:8233'
    VoidLlmUi           = Test-HttpStatus 'http://127.0.0.1:8088/healthz'
    QuartermasterHealth = [bool](Invoke-HttpJson 'http://127.0.0.1:8011/health' $codeRunnerHeaders)
  }
}

switch ($Command) {
  'up' {
    Ensure-LocalEnv
    Invoke-DockerCompose @('up', '-d')
    Start-Quartermaster
    Test-PbkRuntime | Format-List
  }
  'down' {
    Stop-Quartermaster
    Invoke-DockerCompose @('down')
  }
  'quartermaster-start' {
    Start-Quartermaster
  }
  'quartermaster-stop' {
    Stop-Quartermaster
  }
  'check' {
    Test-PbkRuntime | Format-List
  }
}
